version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle update --jobs=4 --retry=3 --path tmp/bundle || \
              bundle install --jobs=4 --retry=3 --path tmp/bundle

      - save_cache:
          paths:
            - ./tmp/bundle
          key: v1-dependencies-{{ checksum "Gemfile" }}

      - run:
          name: run tests
          command: |
            bundle exec rake
